// src/app.vue
<script setup lang="ts">
import Base from '@/layouts/base.vue'
</script>
<template>
  <Base>
  <div class="p-5 mb-4 bg-body-secondary rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">Paxá</h1>
      <p class="col-md-12 fs-4">
        Olá! Meu nome é Lucas, sou especialista em TypeScript, uso frameworks como Vue.js, Astro, React e runtimes como
        Bun e Node.js para criar aplicações web de visual refinado e alta performance.<br />
        <br />
        Sou usuário de Linux desde 1999 e tenho vasta experiência em administração
        de sistemas, garantindo soluções robustas, estáveis e seguras.<br />
        <br />
        Vamos juntos construir soluções inovadoras e impactantes!<br />
        <a href="/contato">Entre em contato</a>.<br />
        <br />
        Paxá<br />
        Full-Stack Web Developer
      </p>
      <button class="btn btn-primary btn-lg" type="button">OK</button>
    </div>
  </div>
  </Base>
</template>

// app/page.tsx
import Image from "next/image";

export default function Home() {
  return (
    <section>
      <a href="/" target="_blank">
        <Image
          src="/images/logo.svg"
          alt="Paxá"
          className="block lg:mt-5 mt-0 lg:mb-5 mb-10 mx-auto sm:float-right sm:ml-5 sm:mb-5 hover:grayscale-0"
          unoptimized
          width={160}
          height={160}
          priority
        />
      </a>
      <div className="prose prose-neutral dark:prose-invert">
        <p>
          Meu nome é Lucas, sou especialista em TypeScript, uso frameworks como Vue.js, Astro, React, Next.js e runtimes como Bun e Node.js para criar aplicações web de visual refinado e alta performance.
        </p>
        <p>
          Sou usuário de Linux desde 1999 e tenho vasta experiência em administração de sistemas, garantindo soluções robustas, estáveis e seguras.
        </p>
        <p>
          Vamos juntos construir soluções inovadoras e impactantes!
        </p>
      </div>
    </section>
  );
}
